
//TODO this is a autogenerated model which is false, create new model by hand (@Adam)

class ShopifyUser {
  Customer customer;

  ShopifyUser({this.customer});

  ShopifyUser.fromJson(Map<String, dynamic> json) {
    customer = json['customer'] != null
        ? new Customer.fromJson(json['customer'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.customer != null) {
      data['customer'] = this.customer.toJson();
    }
    return data;
  }
}

class Customer {
  Addresses addresses;
  bool acceptsMarketing;
  String createdAt;
  String displayName;
  String email;
  String firstName;
  String id;
  String lastName;
  String updatedAt;
  List<String> tags;
  String phone;
  LastIncompleteCheckout lastIncompleteCheckout;

  Customer(
      {this.addresses,
        this.acceptsMarketing,
        this.createdAt,
        this.displayName,
        this.email,
        this.firstName,
        this.id,
        this.lastName,
        this.updatedAt,
        this.tags,
        this.phone,
        this.lastIncompleteCheckout});

  Customer.fromJson(Map<String, dynamic> json) {
    addresses = json['addresses'] != null
        ? new Addresses.fromJson(json['addresses'])
        : null;
    acceptsMarketing = json['acceptsMarketing'];
    createdAt = json['createdAt'];
    displayName = json['displayName'];
    email = json['email'];
    firstName = json['firstName'];
    id = json['id'];
    lastName = json['lastName'];
    updatedAt = json['updatedAt'];
    tags = json['tags'].cast<String>();
    phone = json['phone'];
    lastIncompleteCheckout = json['lastIncompleteCheckout'] != null
        ? new LastIncompleteCheckout.fromJson(json['lastIncompleteCheckout'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.addresses != null) {
      data['addresses'] = this.addresses.toJson();
    }
    data['acceptsMarketing'] = this.acceptsMarketing;
    data['createdAt'] = this.createdAt;
    data['displayName'] = this.displayName;
    data['email'] = this.email;
    data['firstName'] = this.firstName;
    data['id'] = this.id;
    data['lastName'] = this.lastName;
    data['updatedAt'] = this.updatedAt;
    data['tags'] = this.tags;
    data['phone'] = this.phone;
    if (this.lastIncompleteCheckout != null) {
      data['lastIncompleteCheckout'] = this.lastIncompleteCheckout.toJson();
    }
    return data;
  }
}

class Addresses {
  List<Edges> edges;

  Addresses({this.edges});

  Addresses.fromJson(Map<String, dynamic> json) {
    if (json['edges'] != null) {
      edges = new List<Edges>();
      json['edges'].forEach((v) {
        edges.add(new Edges.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.edges != null) {
      data['edges'] = this.edges.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Edges {
  Node node;

  Edges({this.node});

  Edges.fromJson(Map<String, dynamic> json) {
    node = json['node'] != null ? new Node.fromJson(json['node']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.node != null) {
      data['node'] = this.node.toJson();
    }
    return data;
  }
}

class Node {
  String id;
  String address2;
  String address1;
  String city;
  String company;
  String country;
  String countryCodeV2;
  String firstName;
  String lastName;
  Null latitude;
  Null longitude;
  String name;
  String phone;
  String province;
  Null provinceCode;
  String zip;

  Node(
      {this.id,
        this.address2,
        this.address1,
        this.city,
        this.company,
        this.country,
        this.countryCodeV2,
        this.firstName,
        this.lastName,
        this.latitude,
        this.longitude,
        this.name,
        this.phone,
        this.province,
        this.provinceCode,
        this.zip});

  Node.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    address2 = json['address2'];
    address1 = json['address1'];
    city = json['city'];
    company = json['company'];
    country = json['country'];
    countryCodeV2 = json['countryCodeV2'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    latitude = json['latitude'];
    longitude = json['longitude'];
    name = json['name'];
    phone = json['phone'];
    province = json['province'];
    provinceCode = json['provinceCode'];
    zip = json['zip'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['address2'] = this.address2;
    data['address1'] = this.address1;
    data['city'] = this.city;
    data['company'] = this.company;
    data['country'] = this.country;
    data['countryCodeV2'] = this.countryCodeV2;
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['latitude'] = this.latitude;
    data['longitude'] = this.longitude;
    data['name'] = this.name;
    data['phone'] = this.phone;
    data['province'] = this.province;
    data['provinceCode'] = this.provinceCode;
    data['zip'] = this.zip;
    return data;
  }
}

class LastIncompleteCheckout {
  Null completedAt;
  String createdAt;
  String email;
  String id;
  String webUrl;
  TotalPriceV2 totalPriceV2;
  String updatedAt;
  TotalPriceV2 paymentDueV2;
  Null orderStatusUrl;
  String currencyCode;
  Addresses lineItems;

  LastIncompleteCheckout(
      {this.completedAt,
        this.createdAt,
        this.email,
        this.id,
        this.webUrl,
        this.totalPriceV2,
        this.updatedAt,
        this.paymentDueV2,
        this.orderStatusUrl,
        this.currencyCode,
        this.lineItems});

  LastIncompleteCheckout.fromJson(Map<String, dynamic> json) {
    completedAt = json['completedAt'];
    createdAt = json['createdAt'];
    email = json['email'];
    id = json['id'];
    webUrl = json['webUrl'];
    totalPriceV2 = json['totalPriceV2'] != null
        ? new TotalPriceV2.fromJson(json['totalPriceV2'])
        : null;
    updatedAt = json['updatedAt'];
    paymentDueV2 = json['paymentDueV2'] != null
        ? new TotalPriceV2.fromJson(json['paymentDueV2'])
        : null;
    orderStatusUrl = json['orderStatusUrl'];
    currencyCode = json['currencyCode'];
    lineItems = json['lineItems'] != null
        ? new Addresses.fromJson(json['lineItems'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['completedAt'] = this.completedAt;
    data['createdAt'] = this.createdAt;
    data['email'] = this.email;
    data['id'] = this.id;
    data['webUrl'] = this.webUrl;
    if (this.totalPriceV2 != null) {
      data['totalPriceV2'] = this.totalPriceV2.toJson();
    }
    data['updatedAt'] = this.updatedAt;
    if (this.paymentDueV2 != null) {
      data['paymentDueV2'] = this.paymentDueV2.toJson();
    }
    data['orderStatusUrl'] = this.orderStatusUrl;
    data['currencyCode'] = this.currencyCode;
    if (this.lineItems != null) {
      data['lineItems'] = this.lineItems.toJson();
    }
    return data;
  }
}

class TotalPriceV2 {
  String amount;
  String currencyCode;

  TotalPriceV2({this.amount, this.currencyCode});

  TotalPriceV2.fromJson(Map<String, dynamic> json) {
    amount = json['amount'];
    currencyCode = json['currencyCode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['amount'] = this.amount;
    data['currencyCode'] = this.currencyCode;
    return data;
  }
}

class ProductInformation {
  String id;
  int quantity;
  String title;

  ProductInformation({this.id, this.quantity, this.title});

  ProductInformation.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    quantity = json['quantity'];
    title = json['title'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['quantity'] = this.quantity;
    data['title'] = this.title;
    return data;
  }
}